apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdc-mapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdc-mapr
  template:
    metadata:
      labels:
        app: sdc-mapr
    spec:
      containers:
      - name: sdc-mapr
        image: thomasganka/demo-mapr-2
        env:
        - name: SDC_JAVA_OPTS
          value: "-Xmx2g -Xms2g -Dmaprlogin.password.enabled=true"
        - name: SDC_CONF_SDC_BASE_HTTP_URL
          value: http://10.230.17.152:31864
        - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
          value: "true"
        - name: MAPR_CLIENT_CONFIG
          value: "-N hcp.mapr.cluster -c -secure -C 10.230.18.67:7222"
        - name: MAPR_TICKETFILE_LOCATION
          value: /tmp/longlived_ticket/CONTAINER_TICKET
        volumeMounts:
        - name: mapr-truststore
          mountPath: /opt/mapr/conf/ssl_truststore
          subPath: ssl_truststore
        - name: mapr-ticket
          mountPath: /tmp/longlived_ticket
      volumes:
      - name: mapr-truststore
        secret:
          secretName: mapr-truststore-secret
      - name: mapr-ticket
        secret:
          secretName: hpe-ticket-secret
